2025-09-10 18:20:38 - log.log - ERROR - handlers.py:67 - unhandled_exception - code=INTERNAL_SERVER_ERROR path=/user context={'error': "'type' object does not support item assignment"}
2025-09-10 18:21:01 - log.log - INFO - handlers.py:58 - app_error - code=USER_ALREADY_EXISTS path=/user context={}
2025-09-10 18:27:04 - log.log - INFO - handlers.py:58 - app_error - code=USER_ALREADY_EXISTS path=/user context={}
2025-09-10 18:27:41 - log.log - ERROR - handlers.py:67 - unhandled_exception - code=INTERNAL_SERVER_ERROR path=/user/login context={'error': "int() argument must be a string, a bytes-like object or a real number, not 'NoneType'"}
2025-09-10 18:32:43 - log.log - ERROR - handlers.py:67 - unhandled_exception - code=INTERNAL_SERVER_ERROR path=/user/login context={'error': "2 validation errors:\n  {'type': 'missing', 'loc': ('response', 'id'), 'msg': 'Field required', 'input': UserWithTokenOutput(user=UserOut(id=2, name='string2', todo_id_list=[]), access_token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHBpcmVzIjoxNzYwMDg4NzYzLjY5NzgxN30.OdNNX-cbvHc8pNSIRmPViO9C5uGIuXM9nOf3foK8V60')}\n  {'type': 'missing', 'loc': ('response', 'name'), 'msg': 'Field required', 'input': UserWithTokenOutput(user=UserOut(id=2, name='string2', todo_id_list=[]), access_token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHBpcmVzIjoxNzYwMDg4NzYzLjY5NzgxN30.OdNNX-cbvHc8pNSIRmPViO9C5uGIuXM9nOf3foK8V60')}\n"}
2025-09-10 18:35:59 - log.log - ERROR - handlers.py:67 - unhandled_exception - code=INTERNAL_SERVER_ERROR path=/user/me context={'error': "2 validation errors:\n  {'type': 'missing', 'loc': ('response', 'id'), 'msg': 'Field required', 'input': UserWithTokenOutput(user=UserOut(id=2, name='string2', todo_id_list=[]), access_token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHBpcmVzIjoxNzYwMDg4OTU5LjYyODU5Mn0.GBz-c13VZ_igF_JaIiQM2T-crhcmKlfTsDT2H9BnYzQ')}\n  {'type': 'missing', 'loc': ('response', 'name'), 'msg': 'Field required', 'input': UserWithTokenOutput(user=UserOut(id=2, name='string2', todo_id_list=[]), access_token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHBpcmVzIjoxNzYwMDg4OTU5LjYyODU5Mn0.GBz-c13VZ_igF_JaIiQM2T-crhcmKlfTsDT2H9BnYzQ')}\n"}
2025-09-10 18:36:31 - log.log - ERROR - handlers.py:67 - unhandled_exception - code=INTERNAL_SERVER_ERROR path=/user/ context={'error': "Session.refresh() missing 1 required positional argument: 'instance'"}
2025-09-10 18:42:55 - log.log - ERROR - handlers.py:67 - unhandled_exception - code=INTERNAL_SERVER_ERROR path=/todo/ context={'error': "'desciption' is an invalid keyword argument for TodoTable"}
2025-09-10 18:44:08 - log.log - ERROR - handlers.py:67 - unhandled_exception - code=INTERNAL_SERVER_ERROR path=/todo/ context={'error': '1 validation error for Todo\n  Input should be a valid dictionary or instance of Todo [type=model_type, input_value=<Todo(id=1, title=string123, completed=False)>, input_type=TodoTable]\n    For further information visit https://errors.pydantic.dev/2.11/v/model_type'}
2025-09-10 18:47:20 - log.log - ERROR - handlers.py:67 - unhandled_exception - code=INTERNAL_SERVER_ERROR path=/user/ context={'error': "Instance '<UserTable at 0x105425090>' is not persistent within this Session"}
2025-09-10 18:50:07 - log.log - INFO - handlers.py:58 - app_error - code=TODO_NOT_FOUND path=/todo/ context={}
